/* WARNING: This file is autogenerated do not modify manually */
/*
 * S32g2 LinFlexD
 *
 * Copyright (C) 2023 Jose Armando Ruiz <armandorl@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "qemu/osdep.h"
#include "qemu/units.h"
#include "hw/sysbus.h"
#include "hw/irq.h"
#include "migration/vmstate.h"
#include "qemu/log.h"
#include "qemu/timer.h"
#include "qemu/module.h"
#include "hw/misc/s32g2/linFlex-module.h"
#include "hw/qdev-properties.h"
#include "hw/qdev-properties-system.h"

static int debug=0;

enum {
	REG_LINCR1=	0x0,
	REG_BDRL=	0x38,
	REG_BDRM=	0x3C,
	REG_UARTCR1=	0x10,
	REG_UARTSR=	0x14,
	REG_LINSR=	0x8,
};


#define REG_INDEX(offset)         (offset / sizeof(uint32_t))
#define PERFORM_READ(reg)         s->regs[REG_INDEX(reg)] 
#define PERFORM_WRITE(reg, val)   s->regs[REG_INDEX(reg)] = val

#define LINFLEX_LINCR1_INIT   BIT(0)
#define LINFLEX_LINCR1_SLEEP   BIT(1)
#define LINFLEX_LINCR1_MASTER   BIT(4)


#define LINFLEX_UARTCR1_UART   BIT(0)
#define LINFLEX_UARTCR1_TXEN   BIT(4)
#define LINFLEX_UARTCR1_RXEN   BIT(5)
#define LINFLEX_UARTCR1_TXFIFO   BIT(8)
#define LINFLEX_UARTCR1_RXFIFO   BIT(9)
#define LINFLEX_UARTSR_DTFTFF   BIT(1)
#define LINFLEX_UARTSR_DRFRFE   BIT(2)

#define LINFLEX_UART_FIFO_TFC   (1 << 13)
enum {
	LINMODE_SLEEP=0,
	LINMODE_INIT,
       	LINMODE_NORMAL
};

static unsigned int linmode=LINMODE_SLEEP;
static unsigned int is_master=0;
static unsigned int uart_mode=0;
static unsigned int tx_fifo_mode=0;
static unsigned int rx_fifo_mode=0;
unsigned int tx_enable=0;
unsigned int rx_enable=0;

static int serial_can_receive1(void *opaque)
{
    return true;
}

static void serial_receive1(void *opaque, const uint8_t *buf, int size)
{
    S32G2linFlexState *s = S32G2_LINFLEX(opaque);
    int i;
    for (i = 0; i < size; i++) {
/*	    recv_fifo_put(s, buf[i]);*/
            if(debug)printf("%c", buf[i]);
	    if(rx_enable)
	    {
		PERFORM_WRITE(REG_BDRM, buf[i]);
		if(rx_fifo_mode){
			if(debug)printf("fifo mode\n");
			PERFORM_WRITE(REG_UARTCR1, (PERFORM_READ(REG_UARTCR1) | LINFLEX_UART_FIFO_TFC));
			PERFORM_WRITE(REG_UARTSR, (PERFORM_READ(REG_UARTSR) & ~LINFLEX_UARTSR_DRFRFE) );
		}
		else {
			if(debug)printf("buffer mode\n");
			PERFORM_WRITE(REG_UARTSR, PERFORM_READ(REG_UARTSR) | LINFLEX_UARTSR_DRFRFE | BIT(9) );
		}
            	if(debug)printf("Trigger LinFlex IRQ\n");
		qemu_set_irq(s->irq[0], 0); 
		qemu_set_irq(s->irq[0], 1);
	    }
    }
}

static void serial_event(void *opaque, QEMUChrEvent event)
{
    if (event == CHR_EVENT_BREAK){
        if(debug)printf("DEBUG: event_brake\n");
	exit(0);
    }

}

static int serial_be_change(void *opaque)
{
    if(debug)printf("DEBUG: be_change\n");
    return 0;
}

static void linflex_process_lincr1(S32G2linFlexState *s, unsigned int val){

	switch(val&(LINFLEX_LINCR1_INIT|LINFLEX_LINCR1_SLEEP)){
		case LINFLEX_LINCR1_INIT:
			linmode=LINMODE_INIT;
			break;
		case LINFLEX_LINCR1_SLEEP:
			linmode=LINMODE_SLEEP;
			break;
		case LINFLEX_LINCR1_INIT|LINFLEX_LINCR1_SLEEP:
			linmode=LINMODE_SLEEP;
			break;
		case 0:
			linmode=LINMODE_NORMAL;
			break;
		default:
			break;
	}

	if(linmode==LINFLEX_LINCR1_INIT){ 
		is_master=!!(val&LINFLEX_LINCR1_MASTER);
		PERFORM_WRITE(REG_LINSR, LINMODE_INIT<<12);
	}
	else if(linmode==LINMODE_NORMAL){
		PERFORM_WRITE(REG_LINSR, LINMODE_NORMAL<<12);
	}
	else {
		PERFORM_WRITE(REG_LINSR, LINMODE_SLEEP<<12);
	}
	if(debug)printf("Set lincr mode:%d master:%d\n", linmode, is_master);
}

static void linflex_process_uartcr1(S32G2linFlexState *s, unsigned int val){
	tx_enable=!!(val&LINFLEX_UARTCR1_TXEN);
	rx_enable=!!(val&LINFLEX_UARTCR1_RXEN);
	if(linmode==LINMODE_INIT){ 
		uart_mode=!!(val&LINFLEX_UARTCR1_UART);
		tx_fifo_mode=!!(val&LINFLEX_UARTCR1_TXFIFO);
		rx_fifo_mode=!!(val&LINFLEX_UARTCR1_RXFIFO);

		if(tx_fifo_mode){PERFORM_WRITE(REG_UARTSR, (PERFORM_READ(REG_UARTSR) | LINFLEX_UARTSR_DRFRFE) & ~(LINFLEX_UARTSR_DTFTFF)  );
		}
		else {
			PERFORM_WRITE(REG_UARTSR, PERFORM_READ(REG_UARTSR) | LINFLEX_UARTSR_DRFRFE | LINFLEX_UARTSR_DTFTFF  );
		}
		if(debug) printf("Set UART uart:%d txfifo:%d rxfifo:%d txen:%d rxen:%d\n\n",
				uart_mode, tx_fifo_mode, rx_fifo_mode, tx_enable, rx_enable);
	}
}

static uint64_t s32g2_linFlex_read(void *opaque, hwaddr offset,
		unsigned size)
{
	S32G2linFlexState *s = S32G2_LINFLEX(opaque);
	const uint32_t idx = REG_INDEX(offset);
	uint64_t retVal = 0;

	if (idx >= S32G2_LINFLEX_REGS_NUM) {
		qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
				__func__, (uint32_t)offset);
		return 0;
	}

	switch (offset) {
		case REG_BDRM:
			retVal = s->regs[idx];
			PERFORM_WRITE(REG_BDRM, 0);

			if(rx_fifo_mode){
				PERFORM_WRITE(REG_UARTSR, (PERFORM_READ(REG_UARTSR) | LINFLEX_UARTSR_DRFRFE) );
				PERFORM_WRITE(REG_UARTCR1, (PERFORM_READ(REG_UARTCR1) & ~LINFLEX_UART_FIFO_TFC));
			}
			else {
				PERFORM_WRITE(REG_UARTSR, PERFORM_READ(REG_UARTSR) & ~LINFLEX_UARTSR_DRFRFE );
				PERFORM_WRITE(REG_UARTSR, PERFORM_READ(REG_UARTSR) & ~BIT(9) );
			}
			return retVal;
		default:
			break;
	}
	retVal = s->regs[idx];
	if(debug)printf("%s offset=0x%lx val=0x%lx\n", __func__, offset, retVal); 
	return retVal;
}

static void s32g2_linFlex_write(void *opaque, hwaddr offset,
		uint64_t val, unsigned size)
{
	S32G2linFlexState *s = S32G2_LINFLEX(opaque);
	const uint32_t idx = REG_INDEX(offset);

	if (idx >= S32G2_LINFLEX_REGS_NUM) {
		qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
				__func__, (uint32_t)offset);
		return;
	}

	switch (offset) {

		case REG_LINCR1:
			PERFORM_WRITE(REG_LINCR1, val);
			linflex_process_lincr1(s, val);
			;			break;
		case REG_BDRL:
			PERFORM_WRITE(REG_BDRL, val);
			if(tx_fifo_mode) {
				PERFORM_WRITE(REG_UARTSR, (PERFORM_READ(REG_UARTSR) & ~(LINFLEX_UARTSR_DRFRFE | LINFLEX_UARTSR_DTFTFF)));
			} else {
				PERFORM_WRITE(REG_UARTSR, ((PERFORM_READ(REG_UARTSR) | LINFLEX_UARTSR_DTFTFF) & ~LINFLEX_UARTSR_DRFRFE)); 
			}
			/* if(debug)printf("%c", (int)val); */
			qemu_chr_fe_write(&s->chr, (const uint8_t*)&val, 1);
			return; /* TODO: How to use qemu serial output? */
		case REG_UARTCR1:
			PERFORM_WRITE(REG_UARTCR1, val);
			linflex_process_uartcr1(s, val);
			;			break;
		case REG_UARTSR:
			PERFORM_WRITE(REG_UARTSR, (PERFORM_READ(REG_UARTSR) & ~val));
			break;
		case REG_LINSR:
			break;

		default:
			s->regs[idx] = (uint32_t) val;
			break;
	}
	if(debug)printf("%s offset=%lx val=%lx\n", __func__, offset, val);
}

static const MemoryRegionOps s32g2_linFlex_ops = {
	.read = s32g2_linFlex_read,
	.write = s32g2_linFlex_write,
	.endianness = DEVICE_NATIVE_ENDIAN,
	.valid = {
		.min_access_size = 1,
		.max_access_size = 4,
	},
	.impl.min_access_size = 1,
};

static Property serial_properties[] = {
    DEFINE_PROP_CHR("chardev", S32G2linFlexState, chr),
    DEFINE_PROP_END_OF_LIST(),
};

void s32g2_linflex_props_init (S32G2linFlexState *s,
                      qemu_irq irq, Chardev *chr)
{
/*    sysbus_connect_irq(SYS_BUS_DEVICE(s), 0, irq); */
    qdev_prop_set_chr(DEVICE(s), "chardev", chr);
    qemu_chr_fe_set_handlers(&s->chr, serial_can_receive1, serial_receive1,
                             serial_event, serial_be_change, s, NULL, true);
    qemu_chr_fe_set_echo(&s->chr, true);
}

static void s32g2_linFlex_reset(DeviceState *dev)
{
	S32G2linFlexState *s = S32G2_LINFLEX(dev); 

	/* Set default values for registers */
	PERFORM_WRITE(REG_LINCR1,0x82);
	PERFORM_WRITE(REG_BDRL,0x0);
	PERFORM_WRITE(REG_UARTCR1,0x0);
	PERFORM_WRITE(REG_UARTSR,0x4);
	PERFORM_WRITE(REG_LINSR,0x40);

}

static void s32g2_linFlex_init(Object *obj)
{
	SysBusDevice *sbd = SYS_BUS_DEVICE(obj);
	S32G2linFlexState *s = S32G2_LINFLEX(obj);

	/* Memory mapping */
	memory_region_init_io(&s->iomem, OBJECT(s), &s32g2_linFlex_ops, s,
			TYPE_S32G2_LINFLEX, 0x100);
	sysbus_init_mmio(sbd, &s->iomem);
        sysbus_init_irq(sbd, &s->irq[0]);
}

static const VMStateDescription s32g2_linFlex_vmstate = {
	.name = "s32g2_linFlex",
	.version_id = 1,
	.minimum_version_id = 1,
	.fields = (VMStateField[]) {
		VMSTATE_UINT32_ARRAY(regs, S32G2linFlexState, S32G2_LINFLEX_REGS_NUM),
		VMSTATE_END_OF_LIST()
	}
};

static void s32g2_linFlex_class_init(ObjectClass *klass, void *data)
{
	DeviceClass *dc = DEVICE_CLASS(klass);

	dc->reset = s32g2_linFlex_reset;
	dc->vmsd = &s32g2_linFlex_vmstate;
        device_class_set_props(dc, serial_properties);
}

static const TypeInfo s32g2_linFlex_info = {
	.name          = TYPE_S32G2_LINFLEX,
	.parent        = TYPE_SYS_BUS_DEVICE,
	.instance_init = s32g2_linFlex_init,
	.instance_size = sizeof(S32G2linFlexState),
	.class_init    = s32g2_linFlex_class_init,
};

static void s32g2_linFlex_register(void)
{
	type_register_static(&s32g2_linFlex_info);
}

type_init(s32g2_linFlex_register)
