/* WARNING: This file is autogenerated do not modify manually */
/*
 * S32g2 LinFlexD
 *
 * Copyright (C) 2023 Jose Armando Ruiz <armandorl@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "qemu/osdep.h"
#include "qemu/units.h"
#include "hw/sysbus.h"
#include "migration/vmstate.h"
#include "qemu/log.h"
#include "qemu/timer.h"
#include "qemu/module.h"
#include "hw/misc/s32g2/linFlex.h"

enum {
	REG_LINCR1=	0x0,
	REG_UARTCR1=	0x10,
	REG_BDRL=	0x38,
	REG_LINSR=	0x8,
};


#define REG_INDEX(offset)         (offset / sizeof(uint32_t))
#define PERFORM_READ(reg)         s->regs[REG_INDEX(reg)] 
#define PERFORM_WRITE(reg, val)   s->regs[REG_INDEX(reg)] = val

static unsigned int in_init=0;
static unsigned int is_master=0;
static unsigned int uart_mode=0;
static unsigned int tx_fifo_mode=0;
unsigned int tx_enable=0;

static uint64_t s32g2_linFlex_read(void *opaque, hwaddr offset,
                                          unsigned size)
{
    const S32G2linFlexState *s = S32G2_LINFLEX(opaque);
    const uint32_t idx = REG_INDEX(offset);

    if (idx >= S32G2_LINFLEX_REGS_NUM) {
        qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
                      __func__, (uint32_t)offset);
        return 0;
    }

    uint64_t retVal = s->regs[idx];
    /* printf("%s offset=%lx val=%lx\n", __func__, offset, retVal); */
    return retVal;
}

static void s32g2_linFlex_write(void *opaque, hwaddr offset,
                                       uint64_t val, unsigned size)
{
    S32G2linFlexState *s = S32G2_LINFLEX(opaque);
    const uint32_t idx = REG_INDEX(offset);

    if (idx >= S32G2_LINFLEX_REGS_NUM) {
        qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
                      __func__, (uint32_t)offset);
        return;
    }

    switch (offset) {
    
		case REG_LINCR1:
PERFORM_WRITE(REG_LINCR1, val);
			if((val&0x1)==0x1) { in_init=1; PERFORM_WRITE(REG_LINSR, 1<<12);} else { in_init=0;};
if((val&0x10)==0x10) { is_master=1;} else { is_master=0;}
;			break;
		case REG_UARTCR1:
PERFORM_WRITE(REG_UARTCR1, val);
			if(in_init==0x1){ if((val&0x1)==0x1) { uart_mode=1;} else { uart_mode=0;}
if((val&(BIT(8)))==1){tx_fifo_mode=1;} else { tx_fifo_mode=0; }
 if((val&(BIT(4)))==1){tx_enable=0;} else { tx_enable=0; }}
;			break;
		case REG_BDRL:
PERFORM_WRITE(REG_BDRL, val);
			printf("%c", (int)val);return; /* TODO: How to use qemu serial output? */
;			break;
		case REG_LINSR:
			return;

    default:
        /* printf("%s offset=%lx val=%lx\n", __func__, offset, val); */
        s->regs[idx] = (uint32_t) val;
        return;
    }
    /* printf("%s offset=%lx val=%lx\n", __func__, offset, val); */
}

static const MemoryRegionOps s32g2_linFlex_ops = {
    .read = s32g2_linFlex_read,
    .write = s32g2_linFlex_write,
    .endianness = DEVICE_NATIVE_ENDIAN,
    .valid = {
        .min_access_size = 1,
        .max_access_size = 4,
    },
    .impl.min_access_size = 1,
};

static void s32g2_linFlex_reset(DeviceState *dev)
{
    S32G2linFlexState *s = S32G2_LINFLEX(dev); 

    /* Set default values for registers */
    	PERFORM_WRITE(REG_LINCR1,0x82);
	PERFORM_WRITE(REG_UARTCR1,0x0);
	PERFORM_WRITE(REG_BDRL,0x0);
	PERFORM_WRITE(REG_LINSR,0x40);

}

static void s32g2_linFlex_init(Object *obj)
{
    SysBusDevice *sbd = SYS_BUS_DEVICE(obj);
    S32G2linFlexState *s = S32G2_LINFLEX(obj);

    /* Memory mapping */
    memory_region_init_io(&s->iomem, OBJECT(s), &s32g2_linFlex_ops, s,
                           TYPE_S32G2_LINFLEX, 0x100);
    sysbus_init_mmio(sbd, &s->iomem);
}

static const VMStateDescription s32g2_linFlex_vmstate = {
    .name = "s32g2_linFlex",
    .version_id = 1,
    .minimum_version_id = 1,
    .fields = (VMStateField[]) {
        VMSTATE_UINT32_ARRAY(regs, S32G2linFlexState, S32G2_LINFLEX_REGS_NUM),
        VMSTATE_END_OF_LIST()
    }
};

static void s32g2_linFlex_class_init(ObjectClass *klass, void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);

    dc->reset = s32g2_linFlex_reset;
    dc->vmsd = &s32g2_linFlex_vmstate;
}

static const TypeInfo s32g2_linFlex_info = {
    .name          = TYPE_S32G2_LINFLEX,
    .parent        = TYPE_SYS_BUS_DEVICE,
    .instance_init = s32g2_linFlex_init,
    .instance_size = sizeof(S32G2linFlexState),
    .class_init    = s32g2_linFlex_class_init,
};

static void s32g2_linFlex_register(void)
{
    type_register_static(&s32g2_linFlex_info);
}

type_init(s32g2_linFlex_register)
