/* WARNING: This file is autogenerated do not modify manually */
/*
 * S32g2 Clock Generation Module
 *
 * Copyright (C) 2023 Jose Armando Ruiz <armandorl@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "qemu/osdep.h"
#include "qemu/units.h"
#include "hw/sysbus.h"
#include "migration/vmstate.h"
#include "qemu/log.h"
#include "qemu/timer.h"
#include "qemu/module.h"
#include "hw/misc/s32g2/mc_cgm.h"

enum {
	REG_MUX_0_CSS=	0x304,
	REG_MUX_0_CSC=	0x300,
};


#define REG_INDEX(offset)         (offset / sizeof(uint32_t))
#define PERFORM_READ(reg)         s->regs[REG_INDEX(reg)] 
#define PERFORM_WRITE(reg, val)   s->regs[REG_INDEX(reg)] = val



static uint64_t s32g2_mc_cgm_read(void *opaque, hwaddr offset,
                                          unsigned size)
{
    const S32G2mc_cgmState *s = S32G2_MC_CGM(opaque);
    const uint32_t idx = REG_INDEX(offset);

    if (idx >= S32G2_MC_CGM_REGS_NUM) {
        qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
                      __func__, (uint32_t)offset);
        return 0;
    }

    uint64_t retVal = s->regs[idx];
    printf("%s offset=%lx val=%lx\n", __func__, offset, retVal);
    return retVal;
}

static void s32g2_mc_cgm_write(void *opaque, hwaddr offset,
                                       uint64_t val, unsigned size)
{
    S32G2mc_cgmState *s = S32G2_MC_CGM(opaque);
    const uint32_t idx = REG_INDEX(offset);

    if (idx >= S32G2_MC_CGM_REGS_NUM) {
        qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
                      __func__, (uint32_t)offset);
        return;
    }

    switch (offset) {
    
		case REG_MUX_0_CSS:
			return;
		case REG_MUX_0_CSC:
			PERFORM_WRITE(REG_MUX_0_CSC, 0);
;			break;

    default:
        s->regs[idx] = (uint32_t) val;
        printf("%s offset=%lx val=%lx\n", __func__, offset, val);
        break;
    }
}

static const MemoryRegionOps s32g2_mc_cgm_ops = {
    .read = s32g2_mc_cgm_read,
    .write = s32g2_mc_cgm_write,
    .endianness = DEVICE_NATIVE_ENDIAN,
    .valid = {
        .min_access_size = 4,
        .max_access_size = 4,
    },
    .impl.min_access_size = 4,
};

static void s32g2_mc_cgm_reset(DeviceState *dev)
{
    S32G2mc_cgmState *s = S32G2_MC_CGM(dev); 

    /* Set default values for registers */
    	PERFORM_WRITE(REG_MUX_0_CSS,0x80000);
	PERFORM_WRITE(REG_MUX_0_CSC,0x0);

}

static void s32g2_mc_cgm_init(Object *obj)
{
    SysBusDevice *sbd = SYS_BUS_DEVICE(obj);
    S32G2mc_cgmState *s = S32G2_MC_CGM(obj);

    /* Memory mapping */
    memory_region_init_io(&s->iomem, OBJECT(s), &s32g2_mc_cgm_ops, s,
                           TYPE_S32G2_MC_CGM, 0x800);
    sysbus_init_mmio(sbd, &s->iomem);
}

static const VMStateDescription s32g2_mc_cgm_vmstate = {
    .name = "s32g2_mc_cgm",
    .version_id = 1,
    .minimum_version_id = 1,
    .fields = (VMStateField[]) {
        VMSTATE_UINT32_ARRAY(regs, S32G2mc_cgmState, S32G2_MC_CGM_REGS_NUM),
        VMSTATE_END_OF_LIST()
    }
};

static void s32g2_mc_cgm_class_init(ObjectClass *klass, void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);

    dc->reset = s32g2_mc_cgm_reset;
    dc->vmsd = &s32g2_mc_cgm_vmstate;
}

static const TypeInfo s32g2_mc_cgm_info = {
    .name          = TYPE_S32G2_MC_CGM,
    .parent        = TYPE_SYS_BUS_DEVICE,
    .instance_init = s32g2_mc_cgm_init,
    .instance_size = sizeof(S32G2mc_cgmState),
    .class_init    = s32g2_mc_cgm_class_init,
};

static void s32g2_mc_cgm_register(void)
{
    type_register_static(&s32g2_mc_cgm_info);
}

type_init(s32g2_mc_cgm_register)
