/* WARNING: This file is autogenerated do not modify manually */
/*
 * S32g2 Clock Generation Module 2
 *
 * Copyright (C) 2023 Jose Armando Ruiz <armandorl@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "qemu/osdep.h"
#include "qemu/units.h"
#include "hw/sysbus.h"
#include "hw/core/cpu.h"
#include "migration/vmstate.h"
#include "qemu/log.h"
#include "qemu/timer.h"
#include "qemu/module.h"
#include "hw/misc/s32g2/mc_cgm2.h"

static int debug=0;

enum {
	REG_MUX_0_CSC=	0x300,
	REG_MUX_0_CSS=	0x304,
	REG_MUX_1_CSC=	0x340,
	REG_MUX_1_CSS=	0x344,
	REG_MUX_2_CSC=	0x380,
	REG_MUX_2_CSS=	0x384,
	REG_MUX_3_CSC=	0x3c0,
	REG_MUX_3_CSS=	0x3C4,
	REG_MUX_4_CSC=	0x400,
	REG_MUX_4_CSS=	0x404,
	REG_MUX_5_CSC=	0x440,
	REG_MUX_5_CSS=	0x444,
	REG_MUX_6_CSC=	0x480,
	REG_MUX_6_CSS=	0x484,
	REG_MUX_7_CSC=	0x4c0,
	REG_MUX_7_CSS=	0x4c4,
	REG_MUX_8_CSC=	0x500,
	REG_MUX_8_CSS=	0x504,
	REG_MUX_9_CSC=	0x540,
	REG_MUX_9_CSS=	0x544,
};


#define REG_INDEX(offset)         (offset / sizeof(uint32_t))
#define PERFORM_READ(reg)         s->regs[REG_INDEX(reg)] 
#define PERFORM_WRITE(reg, val)   s->regs[REG_INDEX(reg)] = val



static uint64_t s32g2_mc_cgm2_read(void *opaque, hwaddr offset,
		unsigned size)
{
	const S32G2mc_cgm2State *s = S32G2_MC_CGM2(opaque);
	const uint32_t idx = REG_INDEX(offset);

	if (idx >= S32G2_MC_CGM2_REGS_NUM) {
		qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
				__func__, (uint32_t)offset);
		return 0;
	}

	uint64_t retVal = s->regs[idx];
	if(debug)printf("%s offset=0x%lx val=0x%lx size=%d\n", __func__, offset, retVal, size); 
	return retVal;
}

static void s32g2_mc_cgm2_write(void *opaque, hwaddr offset,
		uint64_t val, unsigned size)
{
	S32G2mc_cgm2State *s = S32G2_MC_CGM2(opaque);
	const uint32_t idx = REG_INDEX(offset);

	if (idx >= S32G2_MC_CGM2_REGS_NUM) {
		qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
				__func__, (uint32_t)offset);
		return;
	}

	switch (offset) {

		case REG_MUX_0_CSC:
			PERFORM_WRITE(REG_MUX_0_CSC, val);
			PERFORM_WRITE(REG_MUX_0_CSC, (val & 0xFFFFFFF0)); /* Auto clear */
			PERFORM_WRITE(REG_MUX_0_CSS, (val & 0x3F00000F) | BIT(17));
			;			break;
		case REG_MUX_0_CSS:
			return;
		case REG_MUX_1_CSC:
			PERFORM_WRITE(REG_MUX_1_CSC, val);
			PERFORM_WRITE(REG_MUX_1_CSC, (val & 0xFFFFFFF0)); /* Auto clear */
			PERFORM_WRITE(REG_MUX_1_CSS, (val & 0x3F00000F) | BIT(17));
			;			break;
		case REG_MUX_1_CSS:
			return;
		case REG_MUX_2_CSC:
			PERFORM_WRITE(REG_MUX_2_CSC, val);
			PERFORM_WRITE(REG_MUX_2_CSC, (val & 0xFFFFFFF0)); /* Auto clear */
			PERFORM_WRITE(REG_MUX_2_CSS, (val & 0x3F00000F) | BIT(17));
			;			break;
		case REG_MUX_2_CSS:
			return;
		case REG_MUX_3_CSC:
			PERFORM_WRITE(REG_MUX_3_CSC, val);
			PERFORM_WRITE(REG_MUX_3_CSC, (val & 0xFFFFFFF0)); /* Auto clear */
			PERFORM_WRITE(REG_MUX_3_CSS, (val & 0x3F00000F) | BIT(17));
			;			break;
		case REG_MUX_3_CSS:
			return;
		case REG_MUX_4_CSC:
			PERFORM_WRITE(REG_MUX_4_CSC, val);
			PERFORM_WRITE(REG_MUX_4_CSC, (val & 0xFFFFFFF0)); /* Auto clear */
			PERFORM_WRITE(REG_MUX_4_CSS, (val & 0x3F00000F) | BIT(17));
			;			break;
		case REG_MUX_4_CSS:
			return;
		case REG_MUX_5_CSC:
			PERFORM_WRITE(REG_MUX_5_CSC, val);
			PERFORM_WRITE(REG_MUX_5_CSC, (val & 0xFFFFFFF0)); /* Auto clear */
			PERFORM_WRITE(REG_MUX_5_CSS, (val & 0x3F00000F) | BIT(17));
			;			break;
		case REG_MUX_5_CSS:
			return;
		case REG_MUX_6_CSC:
			PERFORM_WRITE(REG_MUX_6_CSC, val);
			PERFORM_WRITE(REG_MUX_6_CSC, (val & 0xFFFFFFF0)); /* Auto clear */
			PERFORM_WRITE(REG_MUX_6_CSS, (val & 0x3F00000F) | BIT(17));
			;			break;
		case REG_MUX_6_CSS:
			return;
		case REG_MUX_7_CSC:
			PERFORM_WRITE(REG_MUX_7_CSC, val);
			PERFORM_WRITE(REG_MUX_7_CSC, (val & 0xFFFFFFF0)); /* Auto clear */
			PERFORM_WRITE(REG_MUX_7_CSS, (val & 0x3F00000F) | BIT(17));
			;			break;
		case REG_MUX_7_CSS:
			return;
		case REG_MUX_8_CSC:
			PERFORM_WRITE(REG_MUX_8_CSC, val);
			PERFORM_WRITE(REG_MUX_8_CSC, (val & 0xFFFFFFF0)); /* Auto clear */
			PERFORM_WRITE(REG_MUX_8_CSS, (val & 0x3F00000F) | BIT(17));
			;			break;
		case REG_MUX_8_CSS:
			return;
		case REG_MUX_9_CSC:
			PERFORM_WRITE(REG_MUX_9_CSC, val);
			PERFORM_WRITE(REG_MUX_9_CSC, (val & 0xFFFFFFF0)); /* Auto clear */
			PERFORM_WRITE(REG_MUX_9_CSS, (val & 0x3F00000F) | BIT(17));
			;			break;
		case REG_MUX_9_CSS:
			return;

		default:
			printf("%s default action for write offset=%lx val=%lx size=%d\n", __func__, offset, val, size);
			s->regs[idx] = (uint32_t) val;
			return;
	}
	if(debug)printf("%s offset=%lx val=%lx size=%d\n", __func__, offset, val, size);
}

static const MemoryRegionOps s32g2_mc_cgm2_ops = {
	.read = s32g2_mc_cgm2_read,
	.write = s32g2_mc_cgm2_write,
	.endianness = DEVICE_NATIVE_ENDIAN,
	.valid = {
		.min_access_size = 4,
		.max_access_size = 4,
	},
	.impl.min_access_size = 4,
};

static void s32g2_mc_cgm2_reset(DeviceState *dev)
{
	S32G2mc_cgm2State *s = S32G2_MC_CGM2(dev); 

	/* Set default values for registers */
	PERFORM_WRITE(REG_MUX_0_CSC,0x0);
	PERFORM_WRITE(REG_MUX_0_CSS,0x80000);
	PERFORM_WRITE(REG_MUX_1_CSC,0x0);
	PERFORM_WRITE(REG_MUX_1_CSS,0x80000);
	PERFORM_WRITE(REG_MUX_2_CSC,0x0);
	PERFORM_WRITE(REG_MUX_2_CSS,0x80000);
	PERFORM_WRITE(REG_MUX_3_CSC,0x0);
	PERFORM_WRITE(REG_MUX_3_CSS,0x00080000);
	PERFORM_WRITE(REG_MUX_4_CSC,0x00000000);
	PERFORM_WRITE(REG_MUX_4_CSS,0x00080000);
	PERFORM_WRITE(REG_MUX_5_CSC,0x00000000);
	PERFORM_WRITE(REG_MUX_5_CSS,0x00080000);
	PERFORM_WRITE(REG_MUX_6_CSC,0x00000000);
	PERFORM_WRITE(REG_MUX_6_CSS,0x00080000);
	PERFORM_WRITE(REG_MUX_7_CSC,0x00000000);
	PERFORM_WRITE(REG_MUX_7_CSS,0x00080000);
	PERFORM_WRITE(REG_MUX_8_CSC,0x00000000);
	PERFORM_WRITE(REG_MUX_8_CSS,0x00080000);
	PERFORM_WRITE(REG_MUX_9_CSC,0x00000000);
	PERFORM_WRITE(REG_MUX_9_CSS,0x00080000);

}

static void s32g2_mc_cgm2_init(Object *obj)
{
	SysBusDevice *sbd = SYS_BUS_DEVICE(obj);
	S32G2mc_cgm2State *s = S32G2_MC_CGM2(obj);

	/* Memory mapping */
	memory_region_init_io(&s->iomem, OBJECT(s), &s32g2_mc_cgm2_ops, s,
			TYPE_S32G2_MC_CGM2, 0x600);
	sysbus_init_mmio(sbd, &s->iomem);
}

static const VMStateDescription s32g2_mc_cgm2_vmstate = {
	.name = "s32g2_mc_cgm2",
	.version_id = 1,
	.minimum_version_id = 1,
	.fields = (VMStateField[]) {
		VMSTATE_UINT32_ARRAY(regs, S32G2mc_cgm2State, S32G2_MC_CGM2_REGS_NUM),
		VMSTATE_END_OF_LIST()
	}
};

static void s32g2_mc_cgm2_class_init(ObjectClass *klass, void *data)
{
	DeviceClass *dc = DEVICE_CLASS(klass);

	dc->reset = s32g2_mc_cgm2_reset;
	dc->vmsd = &s32g2_mc_cgm2_vmstate;
}

static const TypeInfo s32g2_mc_cgm2_info = {
	.name          = TYPE_S32G2_MC_CGM2,
	.parent        = TYPE_SYS_BUS_DEVICE,
	.instance_init = s32g2_mc_cgm2_init,
	.instance_size = sizeof(S32G2mc_cgm2State),
	.class_init    = s32g2_mc_cgm2_class_init,
};

static void s32g2_mc_cgm2_register(void)
{
	type_register_static(&s32g2_mc_cgm2_info);
}

type_init(s32g2_mc_cgm2_register)
