/* WARNING: This file is autogenerated do not modify manually */
/*
 * S32g2 Clock Generation Module 5
 *
 * Copyright (C) 2023 Jose Armando Ruiz <armandorl@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "qemu/osdep.h"
#include "qemu/units.h"
#include "hw/sysbus.h"
#include "migration/vmstate.h"
#include "qemu/log.h"
#include "qemu/timer.h"
#include "qemu/module.h"
#include "hw/misc/s32g2/mc_cgm5.h"

enum {
	REG_MUX_0_CSS=	0x304,
	REG_MUX_0_CSC=	0x300,
};


#define REG_INDEX(offset)         (offset / sizeof(uint32_t))
#define PERFORM_READ(reg)         s->regs[REG_INDEX(reg)] 
#define PERFORM_WRITE(reg, val)   s->regs[REG_INDEX(reg)] = val



static uint64_t s32g2_mc_cgm5_read(void *opaque, hwaddr offset,
                                          unsigned size)
{
    const S32G2mc_cgm5State *s = S32G2_MC_CGM5(opaque);
    const uint32_t idx = REG_INDEX(offset);

    if (idx >= S32G2_MC_CGM5_REGS_NUM) {
        qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
                      __func__, (uint32_t)offset);
        return 0;
    }

    uint64_t retVal = s->regs[idx];
    /* printf("%s offset=%lx val=%lx\n", __func__, offset, retVal); */
    return retVal;
}

static void s32g2_mc_cgm5_write(void *opaque, hwaddr offset,
                                       uint64_t val, unsigned size)
{
    S32G2mc_cgm5State *s = S32G2_MC_CGM5(opaque);
    const uint32_t idx = REG_INDEX(offset);

    if (idx >= S32G2_MC_CGM5_REGS_NUM) {
        qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
                      __func__, (uint32_t)offset);
        return;
    }

    switch (offset) {
    
		case REG_MUX_0_CSC:
PERFORM_WRITE(REG_MUX_0_CSC, val);
			PERFORM_WRITE(REG_MUX_0_CSC, PERFORM_READ(REG_MUX_0_CSC) & 0xFFFFFFF0); /* Auto clear */
PERFORM_WRITE(REG_MUX_0_CSS, (PERFORM_READ(REG_MUX_0_CSC) & 0x3F000000) | BIT(17));
;			break;

    default:
        /* printf("%s offset=%lx val=%lx\n", __func__, offset, val); */
        s->regs[idx] = (uint32_t) val;
        return;
    }
    /* printf("%s offset=%lx val=%lx\n", __func__, offset, val); */
}

static const MemoryRegionOps s32g2_mc_cgm5_ops = {
    .read = s32g2_mc_cgm5_read,
    .write = s32g2_mc_cgm5_write,
    .endianness = DEVICE_NATIVE_ENDIAN,
    .valid = {
        .min_access_size = 4,
        .max_access_size = 4,
    },
    .impl.min_access_size = 4,
};

static void s32g2_mc_cgm5_reset(DeviceState *dev)
{
    S32G2mc_cgm5State *s = S32G2_MC_CGM5(dev); 

    /* Set default values for registers */
    	PERFORM_WRITE(REG_MUX_0_CSS,0x00080000);
	PERFORM_WRITE(REG_MUX_0_CSC,0x0);

}

static void s32g2_mc_cgm5_init(Object *obj)
{
    SysBusDevice *sbd = SYS_BUS_DEVICE(obj);
    S32G2mc_cgm5State *s = S32G2_MC_CGM5(obj);

    /* Memory mapping */
    memory_region_init_io(&s->iomem, OBJECT(s), &s32g2_mc_cgm5_ops, s,
                           TYPE_S32G2_MC_CGM5, 0x400);
    sysbus_init_mmio(sbd, &s->iomem);
}

static const VMStateDescription s32g2_mc_cgm5_vmstate = {
    .name = "s32g2_mc_cgm5",
    .version_id = 1,
    .minimum_version_id = 1,
    .fields = (VMStateField[]) {
        VMSTATE_UINT32_ARRAY(regs, S32G2mc_cgm5State, S32G2_MC_CGM5_REGS_NUM),
        VMSTATE_END_OF_LIST()
    }
};

static void s32g2_mc_cgm5_class_init(ObjectClass *klass, void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);

    dc->reset = s32g2_mc_cgm5_reset;
    dc->vmsd = &s32g2_mc_cgm5_vmstate;
}

static const TypeInfo s32g2_mc_cgm5_info = {
    .name          = TYPE_S32G2_MC_CGM5,
    .parent        = TYPE_SYS_BUS_DEVICE,
    .instance_init = s32g2_mc_cgm5_init,
    .instance_size = sizeof(S32G2mc_cgm5State),
    .class_init    = s32g2_mc_cgm5_class_init,
};

static void s32g2_mc_cgm5_register(void)
{
    type_register_static(&s32g2_mc_cgm5_info);
}

type_init(s32g2_mc_cgm5_register)
