/* WARNING: This file is autogenerated do not modify manually */
/*
 * S32g2 Mode Entry Module
 *
 * Copyright (C) 2023 Jose Armando Ruiz <armandorl@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "qemu/osdep.h"
#include "qemu/units.h"
#include "hw/sysbus.h"
#include "migration/vmstate.h"
#include "qemu/log.h"
#include "qemu/module.h"
#include "hw/misc/s32g2/mc_me.h"



#define REG_INDEX(offset)   (offset / sizeof(uint32_t))


static uint64_t s32g2_mc_me_read(void *opaque, hwaddr offset,
                                          unsigned size)
{
    const S32G2mc_meState *s = S32G2_MC_ME(opaque);
    const uint32_t idx = REG_INDEX(offset);

    if (idx >= S32G2_MC_ME_REGS_NUM) {
        qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
                      __func__, (uint32_t)offset);
        return 0;
    }

    printf("%s offset=%lx\n", __func__, offset);
    return s->regs[idx];
}

static void s32g2_mc_me_write(void *opaque, hwaddr offset,
                                       uint64_t val, unsigned size)
{
    S32G2mc_meState *s = S32G2_MC_ME(opaque);
    const uint32_t idx = REG_INDEX(offset);

    if (idx >= S32G2_MC_ME_REGS_NUM) {
        qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
                      __func__, (uint32_t)offset);
        return;
    }

    switch (offset) {
    default:
        s->regs[idx] = (uint32_t) val;
        printf("%s offset=%lx val=%lx\n", __func__, offset, val);
        break;
    }
}

static const MemoryRegionOps s32g2_mc_me_ops = {
    .read = s32g2_mc_me_read,
    .write = s32g2_mc_me_write,
    .endianness = DEVICE_NATIVE_ENDIAN,
    .valid = {
        .min_access_size = 4,
        .max_access_size = 4,
    },
    .impl.min_access_size = 4,
};

static void s32g2_mc_me_reset(DeviceState *dev)
{
    /* S32G2mc_meState *s = S32G2_MC_ME(dev); */

    /* Set default values for registers */
}

static void s32g2_mc_me_init(Object *obj)
{
    SysBusDevice *sbd = SYS_BUS_DEVICE(obj);
    S32G2mc_meState *s = S32G2_MC_ME(obj);

    /* Memory mapping */
    memory_region_init_io(&s->iomem, OBJECT(s), &s32g2_mc_me_ops, s,
                           TYPE_S32G2_MC_ME, 12 * KiB);
    sysbus_init_mmio(sbd, &s->iomem);
}

static const VMStateDescription s32g2_mc_me_vmstate = {
    .name = "s32g2_mc_me",
    .version_id = 1,
    .minimum_version_id = 1,
    .fields = (VMStateField[]) {
        VMSTATE_UINT32_ARRAY(regs, S32G2mc_meState, S32G2_MC_ME_REGS_NUM),
        VMSTATE_END_OF_LIST()
    }
};

static void s32g2_mc_me_class_init(ObjectClass *klass, void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);

    dc->reset = s32g2_mc_me_reset;
    dc->vmsd = &s32g2_mc_me_vmstate;
}

static const TypeInfo s32g2_mc_me_info = {
    .name          = TYPE_S32G2_MC_ME,
    .parent        = TYPE_SYS_BUS_DEVICE,
    .instance_init = s32g2_mc_me_init,
    .instance_size = sizeof(S32G2mc_meState),
    .class_init    = s32g2_mc_me_class_init,
};

static void s32g2_mc_me_register(void)
{
    type_register_static(&s32g2_mc_me_info);
}

type_init(s32g2_mc_me_register)
