/* WARNING: This file is autogenerated do not modify manually */
/*
 * S32g2 Mode Entry Module
 *
 * Copyright (C) 2023 Jose Armando Ruiz <armandorl@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "qemu/osdep.h"
#include "qemu/units.h"
#include "hw/sysbus.h"
#include "migration/vmstate.h"
#include "qemu/log.h"
#include "qemu/timer.h"
#include "qemu/module.h"
#include "hw/misc/s32g2/mc_me.h"

enum {
	REG_MODE_STAT=	0xC,
	REG_PRTN0_PUPD=	0x104,
	REG_PRTN3_STAT=	0x708,
	REG_CTRL_KEY=	0x0,
	REG_PRTN3_PUPD=	0x704,
	REG_PRTN3_PCONF=	0x700,
	REG_PRTN0_PCONF=	0x100,
	REG_PRTN0_STAT=	0x108,
	REG_PRTN0_COFB0_STAT=	0x110,
};


#define REG_INDEX(offset)         (offset / sizeof(uint32_t))
#define PERFORM_READ(reg)         s->regs[REG_INDEX(reg)] 
#define PERFORM_WRITE(reg, val)   s->regs[REG_INDEX(reg)] = val

static unsigned int conf_control=0;
static QEMUTimer timer1;
static void trigger_hardware_init(void* opaque){
S32G2mc_meState *s = S32G2_MC_ME(opaque);
unsigned int x=0;
conf_control=0;
x=PERFORM_READ(REG_PRTN3_PUPD) & PERFORM_READ(REG_PRTN3_PCONF);
PERFORM_WRITE(REG_PRTN3_STAT, x);
PERFORM_WRITE(REG_PRTN3_PUPD, 0);
x=PERFORM_READ(REG_PRTN0_PUPD) & PERFORM_READ(REG_PRTN0_PCONF);
PERFORM_WRITE(REG_PRTN0_STAT, x);
PERFORM_WRITE(REG_PRTN0_PUPD, 0);
PERFORM_WRITE(REG_PRTN0_COFB0_STAT, 0xFFFFFFFF);timer_del(&timer1);
timer_deinit(&timer1);
}


static uint64_t s32g2_mc_me_read(void *opaque, hwaddr offset,
                                          unsigned size)
{
    const S32G2mc_meState *s = S32G2_MC_ME(opaque);
    const uint32_t idx = REG_INDEX(offset);

    if (idx >= S32G2_MC_ME_REGS_NUM) {
        qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
                      __func__, (uint32_t)offset);
        return 0;
    }

    uint64_t retVal = s->regs[idx];
    /* printf("%s offset=%lx val=%lx\n", __func__, offset, retVal); */
    return retVal;
}

static void s32g2_mc_me_write(void *opaque, hwaddr offset,
                                       uint64_t val, unsigned size)
{
    S32G2mc_meState *s = S32G2_MC_ME(opaque);
    const uint32_t idx = REG_INDEX(offset);

    if (idx >= S32G2_MC_ME_REGS_NUM) {
        qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
                      __func__, (uint32_t)offset);
        return;
    }

    switch (offset) {
    
		case REG_MODE_STAT:
			return;
		case REG_PRTN3_STAT:
			return;
		case REG_CTRL_KEY:
PERFORM_WRITE(REG_CTRL_KEY, val);
			if(conf_control==0) conf_control++;
if(conf_control==1) {
timer_init_ms(&timer1, QEMU_CLOCK_VIRTUAL, trigger_hardware_init, s);
timer_mod(&timer1, qemu_clock_get_ms(QEMU_CLOCK_VIRTUAL) + 100);}
;			break;
		case REG_PRTN0_STAT:
			return;

    default:
        /* printf("%s offset=%lx val=%lx\n", __func__, offset, val); */
        s->regs[idx] = (uint32_t) val;
        return;
    }
    /* printf("%s offset=%lx val=%lx\n", __func__, offset, val); */
}

static const MemoryRegionOps s32g2_mc_me_ops = {
    .read = s32g2_mc_me_read,
    .write = s32g2_mc_me_write,
    .endianness = DEVICE_NATIVE_ENDIAN,
    .valid = {
        .min_access_size = 4,
        .max_access_size = 4,
    },
    .impl.min_access_size = 4,
};

static void s32g2_mc_me_reset(DeviceState *dev)
{
    S32G2mc_meState *s = S32G2_MC_ME(dev); 

    /* Set default values for registers */
    	PERFORM_WRITE(REG_MODE_STAT,0);
	PERFORM_WRITE(REG_PRTN0_PUPD,0);
	PERFORM_WRITE(REG_PRTN3_STAT,0);
	PERFORM_WRITE(REG_CTRL_KEY,0x5af0);
	PERFORM_WRITE(REG_PRTN3_PUPD,0);
	PERFORM_WRITE(REG_PRTN3_PCONF,0);
	PERFORM_WRITE(REG_PRTN0_PCONF,0x1);
	PERFORM_WRITE(REG_PRTN0_STAT,0x1);
	PERFORM_WRITE(REG_PRTN0_COFB0_STAT,0);

}

static void s32g2_mc_me_init(Object *obj)
{
    SysBusDevice *sbd = SYS_BUS_DEVICE(obj);
    S32G2mc_meState *s = S32G2_MC_ME(obj);

    /* Memory mapping */
    memory_region_init_io(&s->iomem, OBJECT(s), &s32g2_mc_me_ops, s,
                           TYPE_S32G2_MC_ME, 0x800);
    sysbus_init_mmio(sbd, &s->iomem);
}

static const VMStateDescription s32g2_mc_me_vmstate = {
    .name = "s32g2_mc_me",
    .version_id = 1,
    .minimum_version_id = 1,
    .fields = (VMStateField[]) {
        VMSTATE_UINT32_ARRAY(regs, S32G2mc_meState, S32G2_MC_ME_REGS_NUM),
        VMSTATE_END_OF_LIST()
    }
};

static void s32g2_mc_me_class_init(ObjectClass *klass, void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);

    dc->reset = s32g2_mc_me_reset;
    dc->vmsd = &s32g2_mc_me_vmstate;
}

static const TypeInfo s32g2_mc_me_info = {
    .name          = TYPE_S32G2_MC_ME,
    .parent        = TYPE_SYS_BUS_DEVICE,
    .instance_init = s32g2_mc_me_init,
    .instance_size = sizeof(S32G2mc_meState),
    .class_init    = s32g2_mc_me_class_init,
};

static void s32g2_mc_me_register(void)
{
    type_register_static(&s32g2_mc_me_info);
}

type_init(s32g2_mc_me_register)
