/* WARNING: This file is autogenerated do not modify manually */
/*
 * S32g2 Periodic Interrupt Timer Module
 *
 * Copyright (C) 2023 Jose Armando Ruiz <armandorl@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "qemu/osdep.h"
#include "qemu/units.h"
#include "hw/sysbus.h"
#include "hw/irq.h"
#include "migration/vmstate.h"
#include "qemu/log.h"
#include "qemu/timer.h"
#include "qemu/module.h"
#include "hw/misc/s32g2/pit-module.h"
#include "hw/qdev-properties.h"

static int debug=1;

enum {
	REG_TCTRL5=	0x158,
	REG_TCTRL4=	0x148,
	REG_LDVAL0=	0x100,
	REG_LDVAL1=	0x110,
	REG_LDVAL2=	0x120,
	REG_LDVAL3=	0x130,
	REG_LDVAL4=	0x140,
	REG_LDVAL5=	0x150,
	REG_LDVAL6=	0x160,
	REG_TFLG6=	0x16C,
	REG_TCTRL2=	0x128,
	REG_TFLG4=	0x14C,
	REG_TFLG5=	0x15C,
	REG_TFLG2=	0x12C,
	REG_TCTRL6=	0x168,
	REG_TFLG0=	0x10C,
	REG_TFLG1=	0x11C,
	REG_TCTRL3=	0x138,
	REG_CVAL6=	0x164,
	REG_TCTRL1=	0x118,
	REG_CVAL0=	0x104,
	REG_TCTRL0=	0x108,
	REG_CVAL5=	0x154,
	REG_CVAL4=	0x144,
	REG_CVAL2=	0x124,
	REG_CVAL1=	0x114,
	REG_MCR=	0,
	REG_CVAL3=	0x134,
	REG_TFLG3=	0x13C,
	REG_LTMR64H=	0xE0,
	REG_LTMR64L=	0xE4,
};


#define REG_INDEX(offset)         (offset / sizeof(uint32_t))
#define PERFORM_READ(reg)         s->regs[REG_INDEX(reg)] 
#define PERFORM_WRITE(reg, val)   s->regs[REG_INDEX(reg)] = val

#define SET_FLAG(a) PERFORM_WRITE(REG_TFLG##a, 1)

#define PIT_MCR_MDIS     BIT(1)

#define PIT_TCTRL_CHN    BIT(2)
#define PIT_TCTRL_TIE    BIT(1)
#define PIT_TCTRL_TEN    BIT(0)

static void process_expired_timer(unsigned int idx, void* opaque){
	S32G2pitState *s = S32G2_PIT(opaque);
	if(idx==0)SET_FLAG(0);
	if(idx==1)SET_FLAG(1);
	if(idx==2)SET_FLAG(2);
	if(idx==3)SET_FLAG(3);
	if(idx==4)SET_FLAG(4);
	if(idx==5)SET_FLAG(5);
	if(idx==6)SET_FLAG(6);
}


static void s32g2_pit_timer_cb(void *opaque)
{
    S32G2TimerContext *tc = opaque;
    S32G2pitState *s = S32G2_PIT(tc->state);
    int i = tc->index;

    if(debug)printf("Timer %d callback!\n", i); 
    if ((i >= 0) && (i < PIT_MAX_TIMERS)){
	    process_expired_timer(i, s);
	    if( s->timer_enabled[i] && s->timer_int_enabled[i]) {
		    qemu_set_irq(s->irq[0], 1);
	    }
    }
}

static void update_timers(S32G2pitState *s)
{
	int i=0;
	if(s->disabled){
		for(i=0; i<PIT_MAX_TIMERS;i++)
		{
			ptimer_transaction_begin(s->timer[i]);
			ptimer_stop(s->timer[i]);
			ptimer_transaction_commit(s->timer[i]);
		}
	}else{
		for(i=PIT_MAX_TIMERS-1; i>=0;i--){
			if(s->timer_enabled[i])
			{
				if(i<6 && (s->timer_chained[i+1]))
					continue;

				uint64_t limit = 0;
				if((i != 0) && (s->timer_chained[i]))
				{
					limit = (s->timer_loadval[i])<<32;
					limit = limit | (s->timer_loadval[i-1]&0xFFFFFFFF);
				}
				else
				{
					limit = (s->timer_loadval[i-1]&0xFFFFFFFF);
				}
				limit--;
				if(debug)printf("Set timer %d limit %lx\n", i, limit);
				ptimer_transaction_begin(s->timer[i]);
				ptimer_set_limit(s->timer[i], 5000000, 0);
				ptimer_transaction_commit(s->timer[i]);

				ptimer_transaction_begin(s->timer[i]);
				ptimer_run(s->timer[i], 0);
				ptimer_transaction_commit(s->timer[i]);
			}
			else
			{
				ptimer_transaction_begin(s->timer[i]);
				ptimer_stop(s->timer[i]);
				ptimer_transaction_commit(s->timer[i]);
			}
		}
	}
}

static void process_timer_ctl(void *opaque, int idx, uint64_t val){
	S32G2pitState *s = S32G2_PIT(opaque);
	if(idx<PIT_MAX_TIMERS){
		s->timer_enabled[idx]=!!((val&PIT_TCTRL_TEN)==PIT_TCTRL_TEN);
		s->timer_chained[idx]=!!((val&PIT_TCTRL_CHN)==PIT_TCTRL_CHN);
		s->timer_int_enabled[idx]=!!((val&PIT_TCTRL_TIE)==PIT_TCTRL_TIE);
		update_timers(s);

	}
	else
	{
		printf("ERROR: Setting invalid timer index!!!!!!!!\n");
	}

	if(debug){
		printf("Timer %d configured: enabled:%d chained:%d int_enabled:%d (0x%lx)\n",
				idx,
				s->timer_enabled[idx],
				s->timer_chained[idx],
				s->timer_int_enabled[idx],
		                val );
	}
}


static void process_mcr(void* opaque, uint64_t val)
{
	S32G2pitState *s = S32G2_PIT(opaque);
	PERFORM_WRITE(REG_MCR, val);
	s->disabled=!!((val&PIT_MCR_MDIS)==PIT_MCR_MDIS);
	update_timers(s);

}


static uint64_t s32g2_pit_read(void *opaque, hwaddr offset,
		unsigned size)
{
	S32G2pitState *s = S32G2_PIT(opaque);
	const uint32_t idx = REG_INDEX(offset);
	uint32_t timer_idx = PIT_MAX_TIMERS;

	if (idx >= S32G2_PIT_REGS_NUM) {
		qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
				__func__, (uint32_t)offset);
		return 0;
	}

	switch (offset) {

		case REG_TFLG0:
		case REG_TFLG1:
		case REG_TFLG2:
		case REG_TFLG3:
		case REG_TFLG4:
		case REG_TFLG5:
		case REG_TFLG6:
			qemu_set_irq(s->irq[0], 0);
			break;
		case REG_CVAL0:
			timer_idx=0;
			goto reg_cval_label;
		case REG_CVAL1:
			timer_idx=1;
			goto reg_cval_label;
		case REG_CVAL2:
			timer_idx=2;
			goto reg_cval_label;
		case REG_CVAL3:
			timer_idx=3;
			goto reg_cval_label;
		case REG_CVAL4:
			timer_idx=4;
			goto reg_cval_label;
		case REG_CVAL5:
			timer_idx=5;
			goto reg_cval_label;
		case REG_CVAL6:
			timer_idx=6;
reg_cval_label:
			s->regs[idx] = ((s->timer_chained[timer_idx]) ? (ptimer_get_count(s->timer[timer_idx])>>32) : ptimer_get_count(s->timer[timer_idx]))&0xFFFFFFFF;
			break;
		case REG_LTMR64H:
			s->ltmr = ptimer_get_count(s->timer[1]);
			printf("LTMH:%lx\n", s->ltmr);
			s->regs[idx] = (s->ltmr>>32)&0xFFFFFFFF;
			break;
		case REG_LTMR64L:
			s->regs[idx] = (s->ltmr)&0xFFFFFFFF;
			printf("LTML:%lx\n", s->ltmr);
			break;

		default:
			break;
	}
	uint64_t retVal = s->regs[idx];
	if(debug)printf("%s offset=0x%lx val=0x%lx\n", __func__, offset, retVal); 
	return retVal;
}

static void s32g2_pit_write(void *opaque, hwaddr offset,
		uint64_t val, unsigned size)
{
	S32G2pitState *s = S32G2_PIT(opaque);
	const uint32_t idx = REG_INDEX(offset);
	uint32_t timer_idx = PIT_MAX_TIMERS;

	if (idx >= S32G2_PIT_REGS_NUM) {
		qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
				__func__, (uint32_t)offset);
		return;
	}

	switch (offset) {

		case REG_TCTRL0:
			timer_idx=0;
			goto reg_tctrl_label;
		case REG_TCTRL1:
			timer_idx=1;
			goto reg_tctrl_label;
		case REG_TCTRL2:
			timer_idx=2;
			goto reg_tctrl_label;
		case REG_TCTRL3:
			timer_idx=3;
			goto reg_tctrl_label;
		case REG_TCTRL4:
			timer_idx=4;
			goto reg_tctrl_label;
		case REG_TCTRL5:
			timer_idx=5;
			goto reg_tctrl_label;
		case REG_TCTRL6:
			timer_idx=6;
reg_tctrl_label:
			s->regs[idx] = val;
			process_timer_ctl(s, timer_idx, val);
			break;

		case REG_LDVAL0:
			s->timer_loadval[0]=val;
			s->regs[idx] = val;
			break;
		case REG_LDVAL1:
			s->timer_loadval[1]=val;
			s->regs[idx] = val;
			break;
		case REG_LDVAL2:
			s->timer_loadval[2]=val;
			s->regs[idx] = val;
			break;
		case REG_LDVAL3:
			s->timer_loadval[3]=val;
			s->regs[idx] = val;
			break;
		case REG_LDVAL4:
			s->timer_loadval[4]=val;
			s->regs[idx] = val;
			break;
		case REG_LDVAL5:
			s->timer_loadval[5]=val;
			s->regs[idx] = val;
			break;
		case REG_LDVAL6:
			s->timer_loadval[6]=val;
			s->regs[idx] = val;
			break;

		case REG_TFLG0:
		case REG_TFLG1:
		case REG_TFLG2:
		case REG_TFLG3:
		case REG_TFLG4:
		case REG_TFLG5:
		case REG_TFLG6:
			s->regs[idx] = (val&0x1)? 0 : s->regs[idx];
			break;
		case REG_CVAL6:
		case REG_CVAL5:
		case REG_CVAL4:
		case REG_CVAL3:
		case REG_CVAL2:
		case REG_CVAL1:
		case REG_CVAL0:
			break;
		case REG_MCR:
			process_mcr(s, val);
			break;

		default:
			/* printf("%s offset=%lx val=%lx\n", __func__, offset, val); */
			s->regs[idx] = (uint32_t) val;
			return;
	}
	if(debug)printf("%s offset=%lx val=%lx\n", __func__, offset, val);
}

static const MemoryRegionOps s32g2_pit_ops = {
	.read = s32g2_pit_read,
	.write = s32g2_pit_write,
	.endianness = DEVICE_NATIVE_ENDIAN,
	.valid = {
		.min_access_size = 4,
		.max_access_size = 4,
	},
	.impl.min_access_size = 4,
};

static void s32g2_pit_reset(DeviceState *dev)
{
	S32G2pitState *s = S32G2_PIT(dev); 

	/* Set default values for registers */
	PERFORM_WRITE(REG_TCTRL5,0x0);
	PERFORM_WRITE(REG_TCTRL4,0x0);
	PERFORM_WRITE(REG_LDVAL1,0x0);
	PERFORM_WRITE(REG_LDVAL0,0x0);
	PERFORM_WRITE(REG_LDVAL3,0x0);
	PERFORM_WRITE(REG_LDVAL2,0x0);
	PERFORM_WRITE(REG_LDVAL5,0x0);
	PERFORM_WRITE(REG_LDVAL4,0x0);
	PERFORM_WRITE(REG_LDVAL6,0x0);
	PERFORM_WRITE(REG_TFLG6,0x0);
	PERFORM_WRITE(REG_TCTRL2,0x0);
	PERFORM_WRITE(REG_TFLG4,0x0);
	PERFORM_WRITE(REG_TFLG5,0x0);
	PERFORM_WRITE(REG_TFLG2,0x0);
	PERFORM_WRITE(REG_TCTRL6,0x0);
	PERFORM_WRITE(REG_TFLG0,0x0);
	PERFORM_WRITE(REG_TFLG1,0x0);
	PERFORM_WRITE(REG_TCTRL3,0x0);
	PERFORM_WRITE(REG_CVAL6,0x0);
	PERFORM_WRITE(REG_TCTRL1,0x0);
	PERFORM_WRITE(REG_CVAL0,0x0);
	PERFORM_WRITE(REG_TCTRL0,0x0);
	PERFORM_WRITE(REG_CVAL5,0x0);
	PERFORM_WRITE(REG_CVAL4,0x0);
	PERFORM_WRITE(REG_CVAL2,0x0);
	PERFORM_WRITE(REG_CVAL1,0x0);
	PERFORM_WRITE(REG_MCR,0x0);
	PERFORM_WRITE(REG_CVAL3,0x0);
	PERFORM_WRITE(REG_TFLG3,0x0);

}

static Property s32g2_pit_properties[] = {
    DEFINE_PROP_UINT32("clk0-freq", S32G2pitState, clk_freq[0], 10000),
    DEFINE_PROP_UINT32("clk1-freq", S32G2pitState, clk_freq[1], 0),
    DEFINE_PROP_UINT32("clk2-freq", S32G2pitState, clk_freq[2], 0),
    DEFINE_PROP_UINT32("clk3-freq", S32G2pitState, clk_freq[3], 0),
    DEFINE_PROP_END_OF_LIST(),
};

static void s32g2_pit_init(Object *obj)
{
	SysBusDevice *sbd = SYS_BUS_DEVICE(obj);
	S32G2pitState *s = S32G2_PIT(obj);
	int i=0;

	/* Memory mapping */
	memory_region_init_io(&s->iomem, OBJECT(s), &s32g2_pit_ops, s,
			TYPE_S32G2_PIT, 0x200);
	sysbus_init_mmio(sbd, &s->iomem);
        sysbus_init_irq(sbd, &s->irq[0]);
	s->clk_freq[0] = 10000;
	for (i = 0; i < PIT_MAX_TIMERS; i++) {
		S32G2TimerContext *tc = &s->timer_context[i];

		tc->state = s;
		tc->index = i;
		/* s->timer[i] = ptimer_init(s32g2_pit_timer_cb, tc, PTIMER_POLICY_NO_IMMEDIATE_RELOAD|PTIMER_POLICY_NO_IMMEDIATE_TRIGGER); */
		s->timer[i] = ptimer_init(s32g2_pit_timer_cb, tc, PTIMER_POLICY_NO_COUNTER_ROUND_DOWN);
		ptimer_transaction_begin(s->timer[i]);
                ptimer_set_period(s->timer[i], 20000);
                ptimer_set_count(s->timer[i], 10);
		ptimer_stop(s->timer[i]);
		ptimer_transaction_commit(s->timer[i]);
	}
}

static const VMStateDescription s32g2_pit_vmstate = {
	.name = "s32g2_pit",
	.version_id = 1,
	.minimum_version_id = 1,
	.fields = (VMStateField[]) {
		VMSTATE_UINT32_ARRAY(regs, S32G2pitState, S32G2_PIT_REGS_NUM),
		VMSTATE_END_OF_LIST()
	}
};

static void s32g2_pit_class_init(ObjectClass *klass, void *data)
{
	DeviceClass *dc = DEVICE_CLASS(klass);

	dc->reset = s32g2_pit_reset;
        device_class_set_props(dc, s32g2_pit_properties);
	dc->vmsd = &s32g2_pit_vmstate;
}

static const TypeInfo s32g2_pit_info = {
	.name          = TYPE_S32G2_PIT,
	.parent        = TYPE_SYS_BUS_DEVICE,
	.instance_init = s32g2_pit_init,
	.instance_size = sizeof(S32G2pitState),
	.class_init    = s32g2_pit_class_init,
};

static void s32g2_pit_register(void)
{
	type_register_static(&s32g2_pit_info);
}

type_init(s32g2_pit_register)
