/* WARNING: This file is autogenerated do not modify manually */
/*
 * S32g2 SERDES
 *
 * Copyright (C) 2023 Jose Armando Ruiz <armandorl@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "qemu/osdep.h"
#include "qemu/units.h"
#include "hw/sysbus.h"
#include "migration/vmstate.h"
#include "qemu/log.h"
#include "qemu/timer.h"
#include "qemu/module.h"
#include "hw/misc/s32g2/serdes.h"

static int debug=0;

enum {
	REG_XPCS_MII_STAT=	0x2800,
	REG_PE0_LINK_DBG_2=	0x10B4,
	REG_SS_RO_REG_1=	0xE4,
	REG_SS_RO_REG_0=	0xE0,
	REG_XPCS_STAT1=	0x2040,
	REG_XPCS_BITS2=	0x2148,
	REG_XPCS_BITS=	0x20c8,
	REG_XPCS_MII_CTRL=	0x2bfc,
	REG_MPLLA_CTRL=	0x10,
	REG_XPCS_STAT2=	0x2840,
	REG_XPCS_SR_MII_STAT=	0x2000,
	REG_MPLLB_CTRL=	0x14,
	REG_XPCS_SR_MII_CTRL=	0x23fc,
};


#define REG_INDEX(offset)         (offset / sizeof(uint32_t))
#define PERFORM_READ(reg)         s->regs[REG_INDEX(reg)] 
#define PERFORM_WRITE(reg, val)   s->regs[REG_INDEX(reg)] = val



static uint64_t s32g2_serdes_read(void *opaque, hwaddr offset,
                                          unsigned size)
{
    const S32G2serdesState *s = S32G2_SERDES(opaque);
    const uint32_t idx = REG_INDEX(offset);

    if (idx >= S32G2_SERDES_REGS_NUM) {
        qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
                      __func__, (uint32_t)offset);
        return 0;
    }

    uint64_t retVal = s->regs[idx];
    if(debug)printf("%s offset=0x%lx val=0x%lx\n", __func__, offset, retVal); 
    return retVal;
}

static void s32g2_serdes_write(void *opaque, hwaddr offset,
                                       uint64_t val, unsigned size)
{
    S32G2serdesState *s = S32G2_SERDES(opaque);
    const uint32_t idx = REG_INDEX(offset);

    if (idx >= S32G2_SERDES_REGS_NUM) {
        qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
                      __func__, (uint32_t)offset);
        return;
    }

    switch (offset) {
    
		case REG_XPCS_MII_STAT:
PERFORM_WRITE(REG_XPCS_MII_STAT, val);
			break;
;			break;
		case REG_PE0_LINK_DBG_2:
			return;
		case REG_SS_RO_REG_1:
			return;
		case REG_SS_RO_REG_0:
			return;
		case REG_XPCS_STAT1:
			return;
		case REG_XPCS_BITS2:
PERFORM_WRITE(REG_XPCS_BITS2, val);
			break;
;			break;
		case REG_XPCS_BITS:
PERFORM_WRITE(REG_XPCS_BITS, val);
			break;
;			break;
		case REG_XPCS_MII_CTRL:
PERFORM_WRITE(REG_XPCS_MII_CTRL, val);
			PERFORM_WRITE(REG_XPCS_MII_STAT, PERFORM_READ(REG_XPCS_MII_STAT) & ~BIT(15));
;			break;
		case REG_MPLLA_CTRL:
			return;
		case REG_XPCS_STAT2:
			return;
		case REG_XPCS_SR_MII_STAT:
PERFORM_WRITE(REG_XPCS_SR_MII_STAT, val);
			break;
;			break;
		case REG_MPLLB_CTRL:
			return;
		case REG_XPCS_SR_MII_CTRL:
PERFORM_WRITE(REG_XPCS_SR_MII_CTRL, val);
			PERFORM_WRITE(REG_XPCS_SR_MII_STAT, 0); PERFORM_WRITE(REG_XPCS_BITS, 0); PERFORM_WRITE(REG_XPCS_BITS2, 0);
;			break;

    default:
        printf("%s default action for write offset=%lx val=%lx\n", __func__, offset, val);
        s->regs[idx] = (uint32_t) val;
        return;
    }
    if(debug)printf("%s offset=%lx val=%lx\n", __func__, offset, val);
}

static const MemoryRegionOps s32g2_serdes_ops = {
    .read = s32g2_serdes_read,
    .write = s32g2_serdes_write,
    .endianness = DEVICE_NATIVE_ENDIAN,
    .valid = {
        .min_access_size = 1,
        .max_access_size = 4,
    },
    .impl.min_access_size = 1,
};

static void s32g2_serdes_reset(DeviceState *dev)
{
    S32G2serdesState *s = S32G2_SERDES(dev); 

    /* Set default values for registers */
    	PERFORM_WRITE(REG_XPCS_MII_STAT,0x0);
	PERFORM_WRITE(REG_PE0_LINK_DBG_2,0xD1);
	PERFORM_WRITE(REG_SS_RO_REG_1,0x08010000);
	PERFORM_WRITE(REG_SS_RO_REG_0,0x03FCC018);
	PERFORM_WRITE(REG_XPCS_STAT1,0x10);
	PERFORM_WRITE(REG_XPCS_BITS2,0x0);
	PERFORM_WRITE(REG_XPCS_BITS,0x0);
	PERFORM_WRITE(REG_XPCS_MII_CTRL,0x0);
	PERFORM_WRITE(REG_MPLLA_CTRL,0xC0000001);
	PERFORM_WRITE(REG_XPCS_STAT2,0x10);
	PERFORM_WRITE(REG_XPCS_SR_MII_STAT,0x0);
	PERFORM_WRITE(REG_MPLLB_CTRL,0xC0000001);
	PERFORM_WRITE(REG_XPCS_SR_MII_CTRL,0x0);

}

static void s32g2_serdes_init(Object *obj)
{
    SysBusDevice *sbd = SYS_BUS_DEVICE(obj);
    S32G2serdesState *s = S32G2_SERDES(obj);

    /* Memory mapping */
    memory_region_init_io(&s->iomem, OBJECT(s), &s32g2_serdes_ops, s,
                           TYPE_S32G2_SERDES, 0x40000);
    sysbus_init_mmio(sbd, &s->iomem);
}

static const VMStateDescription s32g2_serdes_vmstate = {
    .name = "s32g2_serdes",
    .version_id = 1,
    .minimum_version_id = 1,
    .fields = (VMStateField[]) {
        VMSTATE_UINT32_ARRAY(regs, S32G2serdesState, S32G2_SERDES_REGS_NUM),
        VMSTATE_END_OF_LIST()
    }
};

static void s32g2_serdes_class_init(ObjectClass *klass, void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);

    dc->reset = s32g2_serdes_reset;
    dc->vmsd = &s32g2_serdes_vmstate;
}

static const TypeInfo s32g2_serdes_info = {
    .name          = TYPE_S32G2_SERDES,
    .parent        = TYPE_SYS_BUS_DEVICE,
    .instance_init = s32g2_serdes_init,
    .instance_size = sizeof(S32G2serdesState),
    .class_init    = s32g2_serdes_class_init,
};

static void s32g2_serdes_register(void)
{
    type_register_static(&s32g2_serdes_info);
}

type_init(s32g2_serdes_register)
