/* WARNING: This file is autogenerated do not modify manually */
/*
 * S32g2 System Integration Unit Lite2 1
 *
 * Copyright (C) 2023 Jose Armando Ruiz <armandorl@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "qemu/osdep.h"
#include "qemu/units.h"
#include "hw/sysbus.h"
#include "hw/core/cpu.h"
#include "migration/vmstate.h"
#include "qemu/log.h"
#include "qemu/timer.h"
#include "qemu/module.h"
#include "hw/misc/s32g2/siul2_1.h"
#include "hw/misc/s32g2/iomux_table.h"

static int debug=1;

enum {
	REG_MIDR1=	0x4,
	REG_MIDR2=	0x8,
	REG_DISR0=	0x10,
};


#define REG_INDEX(offset)         (offset / sizeof(uint32_t))
#define PERFORM_READ(reg)         s->regs[REG_INDEX(reg)] 
#define PERFORM_WRITE(reg, val)   s->regs[REG_INDEX(reg)] = val



static const siul2_pad_info_t *s32g2_siul2_1_find_pad(hwaddr offset)
{
    const siul2_pad_info_t *table = siul2_1_pads;
    const size_t count = siul2_1_pads_count;
    const uint32_t addr = (uint32_t)(0x44010000 + offset);
    for (size_t i = 0; i < count; ++i) {
        if (table[i].mscr_addr == addr) {
            return &table[i];
        }
    }
    return NULL;
}

static const siul2_imcr_info_t *s32g2_siul2_1_find_imcr(hwaddr offset)
{
    const siul2_imcr_info_t *table = siul2_1_imcr;
    const size_t count = sizeof(siul2_1_imcr) / sizeof(siul2_1_imcr[0]);
    const uint32_t addr = (uint32_t)(0x44010000 + offset);
    for (size_t i = 0; i < count; ++i) {
        if (table[i].imcr_addr == addr) {
            return &table[i];
        }
    }
    return NULL;
}

static void s32g2_siul2_1_debug_iomux_write(hwaddr offset, uint64_t val)
{
    const siul2_pad_info_t *pad = s32g2_siul2_1_find_pad(offset);
    const siul2_imcr_info_t *imcr = s32g2_siul2_1_find_imcr(offset);
    const uint32_t absolute_addr = (uint32_t)(0x44010000 + offset);
    if (pad) {
        const uint32_t func_sel = (uint32_t)val & 0x7;
        const char *func_name = NULL;
        if (func_sel < 8) {
            func_name = pad->functions[func_sel];
        }
        if (func_name) {
            printf("%s: IOMUX port %s addr=0x%08x val=0x%016llx func=%u (%s)\n",
                   __func__, pad->pad_name, absolute_addr,
                   (unsigned long long)val, func_sel, func_name);
        } else {
            printf("%s: IOMUX port %s addr=0x%08x val=0x%016llx func=%u\n",
                   __func__, pad->pad_name, absolute_addr,
                   (unsigned long long)val, func_sel);
        }
        return;
    }
    if (imcr) {
        const uint32_t source_idx = (uint32_t)val & 0x7;
        const char *source_name = NULL;
        if (source_idx < 8) {
            source_name = imcr->source[source_idx];
        }
        printf("%s: IOMUX IMCR %s addr=0x%08x val=0x%016llx sources=",
               __func__, imcr->function_name, absolute_addr, (unsigned long long)val);
        int first = 1;
        for (size_t i = 0; i < 8; ++i) {
            if (!imcr->source[i]) {
                continue;
            }
            printf("%s%s", first ? "" : ", ", imcr->source[i]);
            first = 0;
        }
        if (source_name) {
            printf(" selected=%s(%u)", source_name, source_idx);
        } else {
            printf(" selected=%u", source_idx);
        }
        printf("\n");
        return;
    }
    printf("%s: IOMUX unknown addr=0x%08x val=0x%016llx\n",
           __func__, absolute_addr, (unsigned long long)val);
}


static uint64_t s32g2_siul2_1_read(void *opaque, hwaddr offset,
                                          unsigned size)
{
    const S32G2siul2_1State *s = S32G2_SIUL2_1(opaque);
    const uint32_t idx = REG_INDEX(offset);

    if (idx >= S32G2_SIUL2_1_REGS_NUM) {
        qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
                      __func__, (uint32_t)offset);
        return 0;
    }

    uint64_t retVal = s->regs[idx];
    if(debug)printf("%s offset=0x%lx val=0x%lx size=%d\n", __func__, offset, retVal, size); 
    return retVal;
}

static void debug_write(const char *func, hwaddr offset,
                        uint64_t val, unsigned size)
{
    if(debug == 1)
    {
        printf("%s offset=%lx val=%lx size=%d\n", func, offset, val, size);
    }
    else if(debug == 2)
    {
        
    }
}

static void s32g2_siul2_1_write(void *opaque, hwaddr offset,
                                       uint64_t val, unsigned size)
{
    S32G2siul2_1State *s = S32G2_SIUL2_1(opaque);
    const uint32_t idx = REG_INDEX(offset);

    if (idx >= S32G2_SIUL2_1_REGS_NUM) {
        qemu_log_mask(LOG_GUEST_ERROR, "%s: out-of-bounds offset 0x%04x\n",
                      __func__, (uint32_t)offset);
        return;
    }

    if (debug) {
        debug_write(__func__, offset, val, size);
    }
    if (debug) { s32g2_siul2_1_debug_iomux_write(offset, val); }

    switch (offset) {
    
		case REG_MIDR1:
			return;
		case REG_MIDR2:
			return;
		case REG_DISR0:
PERFORM_WRITE(REG_DISR0, val);
			PERFORM_WRITE(REG_DISR0, PERFORM_READ(REG_DISR0) & ~val);
;			break;

    default:
        printf("%s default action for write offset=%lx val=%lx size=%d\n", __func__, offset, val, size);
        s->regs[idx] = (uint32_t) val;
        return;
    }
}

static const MemoryRegionOps s32g2_siul2_1_ops = {
    .read = s32g2_siul2_1_read,
    .write = s32g2_siul2_1_write,
    .endianness = DEVICE_NATIVE_ENDIAN,
    .valid = {
        .min_access_size = 1,
        .max_access_size = 4,
    },
    .impl.min_access_size = 1,
};

static void s32g2_siul2_1_reset(DeviceState *dev)
{
    S32G2siul2_1State *s = S32G2_SIUL2_1(dev); 

    /* Set default values for registers */
    	PERFORM_WRITE(REG_MIDR1,0x4c200412);
	PERFORM_WRITE(REG_MIDR2,0x0112c000);
	PERFORM_WRITE(REG_DISR0,0x0);

}

static void s32g2_siul2_1_init(Object *obj)
{
    SysBusDevice *sbd = SYS_BUS_DEVICE(obj);
    S32G2siul2_1State *s = S32G2_SIUL2_1(obj);

    /* Memory mapping */
    memory_region_init_io(&s->iomem, OBJECT(s), &s32g2_siul2_1_ops, s,
                           TYPE_S32G2_SIUL2_1, 0x2000);
    sysbus_init_mmio(sbd, &s->iomem);
}

static const VMStateDescription s32g2_siul2_1_vmstate = {
    .name = "s32g2_siul2_1",
    .version_id = 1,
    .minimum_version_id = 1,
    .fields = (VMStateField[]) {
        VMSTATE_UINT32_ARRAY(regs, S32G2siul2_1State, S32G2_SIUL2_1_REGS_NUM),
        VMSTATE_END_OF_LIST()
    }
};

static void s32g2_siul2_1_class_init(ObjectClass *klass, void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);

    dc->reset = s32g2_siul2_1_reset;
    dc->vmsd = &s32g2_siul2_1_vmstate;
}

static const TypeInfo s32g2_siul2_1_info = {
    .name          = TYPE_S32G2_SIUL2_1,
    .parent        = TYPE_SYS_BUS_DEVICE,
    .instance_init = s32g2_siul2_1_init,
    .instance_size = sizeof(S32G2siul2_1State),
    .class_init    = s32g2_siul2_1_class_init,
};

static void s32g2_siul2_1_register(void)
{
    type_register_static(&s32g2_siul2_1_info);
}

type_init(s32g2_siul2_1_register)
