/* WARNING: This file is autogenerated do not modify manually */
/*
 * S32g2 Periodic Interrupt Timer Module emulation
 *
 * Copyright (C) 2023 Jose Armando Ruiz <armandorl@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef HW_MISC_S32G2_PIT_H
#define HW_MISC_S32G2_PIT_H

#include "qom/object.h"
#include "hw/sysbus.h"
#include "hw/ptimer.h"

/**
 * @name Constants
 * @{
 */

#define PIT_MAX_TIMERS    7
/** Highest register address used by PIT device */
#define S32G2_PIT_REGS_MAXADDR   (0x200)

/** Total number of known registers */
#define S32G2_PIT_REGS_NUM       ((S32G2_PIT_REGS_MAXADDR / \
                                      sizeof(uint32_t)) + 1)

/** @} */

/**
 * @name Object model
 * @{
 */

#define TYPE_S32G2_PIT    "s32g2-pit"
OBJECT_DECLARE_SIMPLE_TYPE(S32G2pitState, S32G2_PIT)

/** @} */

typedef struct S32G2TimerContext {
    S32G2pitState *state;
    int index;
} S32G2TimerContext;
/**
 * S32G2 Periodic Interrupt Timer Module object instance state
 */
struct S32G2pitState {
    /*< private >*/
    SysBusDevice parent_obj;
    /*< public >*/

    /** Maps I/O registers in physical memory */
    MemoryRegion iomem;
    qemu_irq irq[1];
    ptimer_state * timer[PIT_MAX_TIMERS];
    S32G2TimerContext timer_context[PIT_MAX_TIMERS];
    bool timer_enabled[PIT_MAX_TIMERS];
    bool timer_chained[PIT_MAX_TIMERS];
    bool timer_int_enabled[PIT_MAX_TIMERS];
    uint64_t timer_loadval[PIT_MAX_TIMERS];
    uint32_t clk_freq[4];
    uint64_t ltmr;
    bool disabled;

    /** Array of hardware registers */
    uint32_t regs[S32G2_PIT_REGS_NUM];

};

#endif /* HW_MISC_S32G2_PIT_H */
