/* WARNING: This file is autogenerated do not modify manually */
/*
 * S32g2 QSPI Module emulation
 *
 * Copyright (C) 2023 Jose Armando Ruiz <armandorl@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef HW_MISC_S32G2_QSPI_H
#define HW_MISC_S32G2_QSPI_H

#include "qom/object.h"
#include "hw/sysbus.h"
#include "hw/misc/s32g2/qspi_flash.h"
#include "sysemu/block-backend.h"

/**
 * @name Constants
 * @{ 
 */

/** Highest register address used by QSPI device */
#define S32G2_QSPI_REGS_MAXADDR   (0x2000)

/** Total number of known registers */
#define S32G2_QSPI_REGS_NUM       ((S32G2_QSPI_REGS_MAXADDR / \
                                      sizeof(uint32_t)) + 1)

/** @} */

/**
 * @name Object model
 * @{ 
 */

#define TYPE_S32G2_QSPI    "s32g2-qspi"
OBJECT_DECLARE_SIMPLE_TYPE(S32G2qspiState, S32G2_QSPI)

/** @} */

/**
 * S32G2 QSPI Module object instance state
 */
struct S32G2qspiState {
    /*< private >*/
    SysBusDevice parent_obj;
    /*< public >*/

    /** Maps I/O registers in physical memory */
    MemoryRegion iomem;

    /** Array of hardware registers */
    uint32_t regs[S32G2_QSPI_REGS_NUM];

    /** Bus used to attach a simulated external SPI/QSPI NOR flash chip */
    S32G2QspiFlashBus flash_bus;

    /** AHB memory-mapped flash window, set by the board from its XIP RAM/ROM */
    uint8_t *xip_storage;
    uint64_t xip_size;

    /** Software model of the IP TX FIFO (TBDR pushes) used for Page Program */
    uint8_t tbdr_fifo[64];
    uint32_t tbdr_fifo_len;

    /** Write Enable Latch, set by WREN(0x06)/cleared by WRDI(0x04) or after program/erase */
    uint8_t flash_wel;

    /** Backing image (board's boot BlockBackend) that program/erase writes persist to */
    BlockBackend *backing_blk;

};

#endif /* HW_MISC_S32G2_QSPI_H */
